# base_url.yaml file

BASE_URL_INSIGHT_PROD: 'https://smartinsightsv2.askdata.com/rules?agentId='
BASE_URL_INSIGHT_QA: 'https://smartinsightsv2-qa.askdata.com/rules?agentId='
BASE_URL_INSIGHT_DEV: 'https://smartinsightsv2-dev.askdata.com/rules?agentId='
BASE_URL_AUTH_PROD: 'https://smartfeed.askdata.com'
BASE_URL_AUTH_QA: 'https://smartfeed-qa.askdata.com'
BASE_URL_AUTH_DEV: 'https://smartfeed-dev.askdata.com'
BASE_URL_AGENT_PROD': 'https://smartbot.askdata.com/agent?page=0&size=300'
BASE_URL_AGENT_QA: 'https://smartbot-qa.askdata.com/agent?page=0&size=300'
BASE_URL_AGENT_DEV': 'https://smartbot.askdata.com/agent?page=0&size=300'

